server:
  port: 8090

spring:
  application:
    name: report-service

  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/EcommerceDB?createDatabaseIfNotExist=true
    username: root
    password: ecommerce123

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

app:
  sales-service:
    base-url: http://order-pay-service:8088
  user-service:
    base-url: http://auth-service:8081
  product-service:
    base-url: http://product-service:8089
